version: '3.8'

services:
  elasticsearch:
    build: .
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - monitoring-network
    ports:
      - "9200:9200"

  logstash:
    build: .
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - monitoring-network
    ports:
      - "5044:5044"
      - "9600:9600"

  kibana:
    build: .
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - monitoring-network
    ports:
      - "5601:5601"

  wazuh-manager:
    build: .
    container_name: wazuh-manager
    networks:
      - monitoring-network
    ports:
      - "1514:1514/udp"
      - "55000:55000/tcp"

  nifi:
    build: .
    container_name: nifi
    networks:
      - monitoring-network
    ports:
      - "8080:8080"

volumes:
  esdata:

networks:
  monitoring-network:
    external: true
